//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonalDbEntities2 : DbContext
    {
        public PersonalDbEntities2()
            : base("name=PersonalDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TblEducation> TblEducation { get; set; }
        public DbSet<TblExperience> TblExperience { get; set; }
        public DbSet<TblFeature> TblFeature { get; set; }
        public DbSet<TblImage> TblImage { get; set; }
        public DbSet<TblSkill> TblSkill { get; set; }
        public DbSet<TblTestimonial> TblTestimonial { get; set; }
    }
}
