//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMember
    {
        public TblMember()
        {
            this.TblMemberRole = new HashSet<TblMemberRole>();
        }
    
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public string MemberSurname { get; set; }
        public string MemberPassword { get; set; }
        public string MemberMail { get; set; }
        public Nullable<int> Lockout_End { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
    
        public virtual ICollection<TblMemberRole> TblMemberRole { get; set; }
    }
}
