//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRole
    {
        public TblRole()
        {
            this.TblMemberRole = new HashSet<TblMemberRole>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<TblMemberRole> TblMemberRole { get; set; }
    }
}
